# Generated by Django 5.2.3 on 2025-06-17 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название жанра')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('author', models.CharField(max_length=100, verbose_name='Автор')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Шифр произведения')),
                ('year', models.PositiveIntegerField(verbose_name='Год издания')),
                ('pages', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество страниц')),
                ('medium', models.CharField(choices=[('P', 'Бумажная'), ('E', 'Электронная'), ('A', 'Аудио')], max_length=1, verbose_name='Носитель')),
                ('wholesale_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Оптовая цена')),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Розничная цена')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='В наличии')),
                ('sold', models.PositiveIntegerField(default=0, verbose_name='Продано')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.genre', verbose_name='Жанр')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа')),
                ('completed', models.BooleanField(default=False, verbose_name='Выполнен')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='Книга')),
            ],
        ),
    ]
